name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "ARM64-linux",
            os: [self-hosted, linux, ARM64],
            triplet: ARM64-linux,
            cc: "/usr/bin/gcc-9",
            cxx: "/usr/bin/g++-9"
          }

    steps:
      - name: Setup - cmake
        uses: lukka/get-cmake@latest

      - name: Setup - lcov
        shell: bash
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt update && apt install --yes lcov

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: CC=/usr/bin/gcc-9 CXX=/usr/bin/g++-9 cmake $GITHUB_WORKSPACE -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBUILD_TESTS=1

      - name: Build All
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --target rpi4_status_display_tests -- -j 4

      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ./rpi4_status_display_tests

      - name: Code Coverage - Generation
        shell: bash
        env:
          INPUT_GCOV_PATH: /usr/bin/gcov
          INPUT_OUTPUT_LCOV_INFO: coverage.info
          INPUT_REMOVE_PATTERNS: 3rdparty,tests,build/_deps
        run: tools/cmake_support/lcov.sh

      - name: Code Coverage - Upload to codecov.io
        shell: bash
        working-directory: ${{github.workspace}}
        run: bash <(curl -s https://codecov.io/bash) -X gcov -Z -f coverage.info
